---
title: "RankDivergence"
author: "Mark Hibbins (adopted from Rebecca L. Young)"
date: "8/4/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
remove(list=ls())
```


```{r libraries}
#BiocManager::install("RRHO")
library(tidyverse)
library(dplyr)
library(ggplot2)
library(readr)
library(RRHO)
library(viridis)
```

load cavity nesting differential expression outputs

```{r data}
  
 #Sparrow comparison
 sparrow_results <- read.csv(
   "C:/Users/18126/OneDrive - University of Toronto/Projects/bird_expression/datasets/RRHO/CN_Females_DEGs_Sparrows.csv", header = TRUE)
 sparrow_results<-cbind.data.frame(sparrow_results, 
                                        SparrowRank = rank(sparrow_results$ET_F_vs_HS_F_log2FoldChange), 
                                        sign=ifelse(sparrow_results$ET_F_vs_HS_F_log2FoldChange < 0, -1, 1))
 sparrow_results <- na.omit(sparrow_results)
   sparrow_results<-sparrow_results%>%
     dplyr::mutate(sparrowRRHO = ET_F_vs_HS_F_padj*sign) %>%
   dplyr::rename(sparrowFC=ET_F_vs_HS_F_log2FoldChange, 
                 SparrowNonadjP = ET_F_vs_HS_F_padj) 

   #Swallow comparison
 swallow_results <- read.csv(
   "C:/Users/18126/OneDrive - University of Toronto/Projects/bird_expression/datasets/RRHO/CN_Females_DEGs_Swallows.csv", header = TRUE)
 swallow_results<-cbind.data.frame(swallow_results, 
                                        SwallowRank = rank(swallow_results$TS_F_vs_BS_F_log2FoldChange), 
                                        sign=ifelse(swallow_results$TS_F_vs_BS_F_log2FoldChange < 0, -1, 1))
 swallow_results <- na.omit(swallow_results)
   swallow_results<-swallow_results%>%
     dplyr::mutate(swallowRRHO = TS_F_vs_BS_F_padj*sign) %>%
   dplyr::rename(swallowFC=TS_F_vs_BS_F_log2FoldChange, 
                 swallowNonadjP = TS_F_vs_BS_F_padj) 

  #Thrush comparison
    thrush_results <- read.csv(
   "C:/Users/18126/OneDrive - University of Toronto/Projects/bird_expression/datasets/RRHO/CN_Females_DEGs_Thrushes.csv", header = TRUE)
 thrush_results<-cbind.data.frame(thrush_results, 
                                        ThrushRank = rank(thrush_results$BB_F_vs_RO_F_log2FoldChange), 
                                        sign=ifelse(thrush_results$BB_F_vs_RO_F_log2FoldChange < 0, -1, 1))
 thrush_results <- na.omit(thrush_results)
   thrush_results<-thrush_results%>%
     dplyr::mutate(thrushRRHO = BB_F_vs_RO_F_padj*sign) %>%
   dplyr::rename(thrushFC=BB_F_vs_RO_F_log2FoldChange, 
                 thrushNonadjP = BB_F_vs_RO_F_padj) 
   
  #Warbler comparison
   warbler_results <- read.csv(
   "C:/Users/18126/OneDrive - University of Toronto/Projects/bird_expression/datasets/RRHO/CN_Females_DEGs_Warblers.csv", header = TRUE)
 warbler_results<-cbind.data.frame(warbler_results, 
                                        WarblerRank = rank(warbler_results$PW_F_vs_YW_F_log2FoldChange), 
                                        sign=ifelse(warbler_results$PW_F_vs_YW_F_log2FoldChange < 0, -1, 1))
 warbler_results <- na.omit(warbler_results)
   warbler_results<-warbler_results%>%
     dplyr::mutate(warblerRRHO = PW_F_vs_YW_F_padj*sign) %>%
   dplyr::rename(warblerFC=PW_F_vs_YW_F_log2FoldChange, 
                 warblerNonadjP = PW_F_vs_YW_F_padj) 
   
  #Wren comparison
    wren_results <- read.csv(
   "C:/Users/18126/OneDrive - University of Toronto/Projects/bird_expression/datasets/RRHO/CN_Females_DEGs_Wrens.csv", header = TRUE)
 wren_results<-cbind.data.frame(wren_results, 
                                        WrenRank = rank(wren_results$HW_F_vs_CW_F_log2FoldChange), 
                                        sign=ifelse(wren_results$HW_F_vs_CW_F_log2FoldChange < 0, -1, 1))
 wren_results <- na.omit(wren_results)
   wren_results<-wren_results%>%
     dplyr::mutate(wrenRRHO = HW_F_vs_CW_F_padj*sign) %>%
   dplyr::rename(wrenFC=HW_F_vs_CW_F_log2FoldChange, 
                 wrenNonadjP = HW_F_vs_CW_F_padj) 

   
```

```{r RRHO}
x = sparrow_results %>%
  dplyr::select(GeneName, sparrowRRHO)
y = swallow_results %>%
  dplyr::select(GeneName, swallowRRHO)
sparrow_swallow<-RRHO( x, y,  
      labels = c("Sparrows (ET vs. SH)",
                 "Swallows (TS vs. BS)"),  
      alternative = 'enrichment', 
      plots = TRUE,  outputdir = "C:/Users/18126/OneDrive - University of Toronto/Projects/bird_expression/results/RRHO/female_only", 
      BY = TRUE, 
      log10.ind=FALSE)

x = sparrow_results %>%
  dplyr::select(GeneName, sparrowRRHO)
y = thrush_results %>%
  dplyr::select(GeneName, thrushRRHO)
sparrow_thrush<-RRHO( x, y,  
      labels = c("Sparrows (ET vs. SH)",
                 "Thrushes (BB vs. RO)"),  
      alternative = 'enrichment', 
      plots = TRUE,  outputdir = "C:/Users/18126/OneDrive - University of Toronto/Projects/bird_expression/results/RRHO/female_only", 
      BY = TRUE, 
      log10.ind=FALSE)

x = sparrow_results %>%
  dplyr::select(GeneName, sparrowRRHO)
y = warbler_results %>%
  dplyr::select(GeneName, warblerRRHO)
sparrow_warbler<-RRHO( x, y,  
      labels = c("Sparrows (ET vs. SH)",
                 "Warblers (PW vs. YW)"),  
      alternative = 'enrichment', 
      plots = TRUE,  outputdir = "C:/Users/18126/OneDrive - University of Toronto/Projects/bird_expression/results/RRHO/female_only", 
      BY = TRUE, 
      log10.ind=FALSE)

x = sparrow_results %>%
  dplyr::select(GeneName, sparrowRRHO)
y = wren_results %>%
  dplyr::select(GeneName, wrenRRHO)
sparrow_wren<-RRHO( x, y,  
      labels = c("Sparrows (ET vs. SH)",
                 "Wrens (HW vs. CW)"),  
      alternative = 'enrichment', 
      plots = TRUE,  outputdir = "C:/Users/18126/OneDrive - University of Toronto/Projects/bird_expression/results/RRHO/female_only", 
      BY = TRUE, 
      log10.ind=FALSE)

x = swallow_results %>%
  dplyr::select(GeneName, swallowRRHO)
y = thrush_results %>%
  dplyr::select(GeneName, thrushRRHO)
swallow_thrush<-RRHO( x, y,  
      labels = c("Swallows (TS vs. BS)",
                 "Thrushes (BB vs. RO)"),  
      alternative = 'enrichment', 
      plots = TRUE,  outputdir = "C:/Users/18126/OneDrive - University of Toronto/Projects/bird_expression/results/RRHO/female_only", 
      BY = TRUE, 
      log10.ind=FALSE)

x = swallow_results %>%
  dplyr::select(GeneName, swallowRRHO)
y = warbler_results %>%
  dplyr::select(GeneName, warblerRRHO)
swallow_warbler<-RRHO( x, y,  
      labels = c("Swallows (TS vs. BS)",
                 "Warbler (PW vs. YW)"),  
      alternative = 'enrichment', 
      plots = TRUE,  outputdir = "C:/Users/18126/OneDrive - University of Toronto/Projects/bird_expression/results/RRHO/female_only", 
      BY = TRUE, 
      log10.ind=FALSE)

x = swallow_results %>%
  dplyr::select(GeneName, swallowRRHO)
y = wren_results %>%
  dplyr::select(GeneName, wrenRRHO)
swallow_wren<-RRHO( x, y,  
      labels = c("Swallows (TS vs. BS)",
                 "Wrens (HW vs. CW)"),  
      alternative = 'enrichment', 
      plots = TRUE,  outputdir = "C:/Users/18126/OneDrive - University of Toronto/Projects/bird_expression/results/RRHO/female_only", 
      BY = TRUE, 
      log10.ind=FALSE)

x = thrush_results %>%
  dplyr::select(GeneName, thrushRRHO)
y = warbler_results %>%
  dplyr::select(GeneName, warblerRRHO)
thrush_warbler<-RRHO( x, y,  
      labels = c("Thrushes (BB vs. RO)",
                 "Warblers (PW vs. YW)"),  
      alternative = 'enrichment', 
      plots = TRUE,  outputdir = "C:/Users/18126/OneDrive - University of Toronto/Projects/bird_expression/results/RRHO/female_only", 
      BY = TRUE, 
      log10.ind=FALSE)

x = thrush_results %>%
  dplyr::select(GeneName, thrushRRHO)
y = wren_results %>%
  dplyr::select(GeneName, wrenRRHO)
thrush_wren<-RRHO( x, y,  
      labels = c("Thrushes (BB vs. RO)",
                 "Wrens (HW vs. CW)"),  
      alternative = 'enrichment', 
      plots = TRUE,  outputdir = "C:/Users/18126/OneDrive - University of Toronto/Projects/bird_expression/results/RRHO/female_only", 
      BY = TRUE, 
      log10.ind=FALSE)

x = warbler_results %>%
  dplyr::select(GeneName, warblerRRHO)
y = wren_results %>%
  dplyr::select(GeneName, wrenRRHO)
warbler_wren<-RRHO( x, y,  
      labels = c("Warblers (PW vs. YW)",
                 "Wrens (HW vs. CW)"),  
      alternative = 'enrichment', 
      plots = TRUE,  outputdir = "C:/Users/18126/OneDrive - University of Toronto/Projects/bird_expression/results/RRHO/female_only", 
      BY = TRUE, 
      log10.ind=FALSE)

sparrow_swallow_pval <- pvalRRHO(sparrow_swallow, 100)
sparrow_thrush_pval <- pvalRRHO(sparrow_thrush, 100)
sparrow_warbler_pval <- pvalRRHO(sparrow_warbler, 100)
sparrow_wren_pval <- pvalRRHO(sparrow_wren, 100)
swallow_thrush_pval <- pvalRRHO(swallow_thrush, 100)
swallow_warbler_pval <- pvalRRHO(swallow_warbler, 100)
swallow_wren_pval <- pvalRRHO(swallow_wren, 100)
thrush_warbler_pval <- pvalRRHO(thrush_warbler, 100)
thrush_wren_pval <- pvalRRHO(thrush_wren, 100)
warbler_wren_pval <- pvalRRHO(warbler_wren, 100)
```

```{r zero}

# I don't know what the rest of these code blocks do
x<-limma_FacNon_results %>%
  dplyr::mutate(FacNonRRHOrank = rank(FacNonRRHO)) %>%
  dplyr::select(X, FacNonRRHOrank)

y<-limma_OblNon_results %>%
  dplyr::mutate(OblNonRRHOrank = rank(OblNonRRHO)) %>%
  dplyr::select(X, OblNonRRHOrank)

z<-limma_OblFac_results %>%
  dplyr::mutate(OblFacRRHOrank = rank(OblFacRRHO)) %>%
  dplyr::select(X, OblFacRRHOrank)

x<-full_join(x,y)
ranks<-full_join(x,z)

colnames(ranks) #check order

ranks<-ranks %>% 
  dplyr::mutate(FacNon = ntile(FacNonRRHOrank, 103), 
                OblNon = ntile(OblNonRRHOrank, 103), 
                OblFac = ntile(OblFacRRHOrank, 103))

#look for the zero bin to identify the separation between up and down regulation
FacNon_bins<-full_join(limma_FacNon_results, 
                       ranks)

FacNon_bins<- 
  FacNon_bins %>%
  dplyr::group_by(FacNon )%>%
  dplyr::summarise(FacNon_min=min(FacNonFC), 
                   FacNon_max=max(FacNonFC), 
                   FacNon_mean=mean(FacNonFC))

OblNon_bins<-full_join(limma_OblNon_results, 
                       ranks)

OblNon_bins<- 
  OblNon_bins %>%
  dplyr::group_by(OblNon )%>%
  dplyr::summarise(OblNon_min=min(OblNonFC), 
                   OblNon_max=max(OblNonFC), 
                   OblNon_mean=mean(OblNonFC))

OblFac_bins<-full_join(limma_OblFac_results, 
                       ranks)

OblFac_bins<- 
  OblFac_bins %>%
  dplyr::group_by(OblFac )%>%
  dplyr::summarise(OblFac_min=min(OblFacFC), 
                   OblFac_max=max(OblFacFC), 
                   OblFac_mean=mean(OblFacFC))

#down- to up-regulation switch point for each lineage
#I use this sometimes in plotting to indicate the bin at which the data switch from down to up regulation
FacNon_zero=48.5
OblNon_zero=53.5
OblFac_zero=57.5
```

```{r RRHOplots}
#pdf("RRHO_enrichmentplots.pdf")
lattice::levelplot(FacNon_OblNon$hypermat.by,  
                   col.regions=colorRampPalette(c("#003366",
                                                  "blue",
                                                  "green",
                                                  "yellow", 
                                                  "red", 
                                                  "firebrick")),  
                   xlab="Facultative versus Non-cleaners",
                   ylab="Obligate versus Non-cleaners")
                   # panel = function(...){ ###this function plots the levelplot and then adds lines
                   #   panel.levelplot(...)
                   #   panel.abline(h = OblNon_zero, lty = "dashed", lwd=2, col="white")
                   #   panel.abline(v = FacNon_zero, lty = "dashed", lwd=2, col="white")})


lattice::levelplot(FacNon_OblFac$hypermat.by,  
                   col.regions=colorRampPalette(c("#003366",
                                                  "blue",
                                                  "green",
                                                  "yellow", 
                                                  "red", 
                                                  "firebrick")), 
                   xlab="Facultative versus Non-cleaners",
                   ylab="Obligate versus Facultative Cleaners")
#dev.off()

```

```{r mergeRanks}
limmaRanks<-full_join(limma_OblNon_results,
                      limma_FacNon_results, 
                      by = 'X')
                      
limmaRanks<-full_join(limmaRanks, 
                      limma_OblFac_results, 
                      by = 'X')

ggplot(limmaRanks, aes(x=FacNonRank, 
                       y=OblNonRank))+
  geom_point() +
  NULL

ggplot(limmaRanks, aes(x=FacNonRank, 
                       y=OblFacRank))+
  geom_point() +
  NULL
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
