# -*- coding: utf-8 -*-
"""
Created on Tue Dec 21 14:03:48 2021

@author: Mark Hibbins
"""

### This script takes the csv file generated by parse_bird_expression_results.py,
### applies multiple testing corrections, and writes the final results to a 
### new csv file. 

import statsmodels.stats.multitest as smm
import csv

raw_result_lines = [] 

with open("C:/Users/18126/OneDrive - University of Toronto/Projects/bird_expression/results/bird_expression_agg_model_raw_results.txt", "r") as raw_results:
    for line in raw_results:
        raw_result_lines.append(line.split())
        
raw_pvals = []


for i in range(len(raw_result_lines)):
    
    pval = raw_result_lines[i][8]
    
    if pval == "<1e-04" or pval == "1e-04":
        raw_pvals.append(0.0001)
    else:
        raw_pvals.append(pval)
        
raw_pvals = [float(pval) for pval in raw_pvals]

tests, corrected_pvals = smm.fdrcorrection(raw_pvals)

results = []

for i in range(len(corrected_pvals)):
    if corrected_pvals[i] < 0.05 and raw_result_lines[i][3] != '(Intercept)':
        total_results = raw_result_lines[i]
        total_results.append(corrected_pvals[i])
        results.append(total_results)
        
with open("C:/Users/18126/OneDrive - University of Toronto/Projects/bird_expression/results/bird_expression_agg_models_fdr_results.csv", "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerows(results)
